### ISSUE TITLE
can you automate existing instagram app?

### ISSUE THREAD

**Issue by Nisthar** [zhehaowang/themistalkles#1]
what is the app package name and activity name of instagram app?

**Comment by zhehaowang** [comment]
Check out https://github.com/zhehaowang/themistalkles/blob/master/instagram_session.json .
It is only for a particular version of Instagram, which you should still be able to find online.

**Comment by Nisthar** [comment]
@zhehaowang it uses a fresh new install. Right? I am looking to use existing app thats logged in
Thanks

**Comment by zhehaowang** [comment]
Yeah my example uses a new app installed on an android emulator.

Existing app should work, too, you could check out guides on using appium with a real device.

I doubt the ActivityName changed but some steps are no longer needed and element names certainly could have.

**Comment by Nisthar** [comment]
Can you tell me how'd you find the activity name ?

**Comment by zhehaowang** [comment]
I used adb shell with an emulator. Does [this](https://stackoverflow.com/questions/33441138/how-to-find-out-activity-names-in-a-package-android-adb-shell) help?
